name: Deploy GP

on:
  watch:
    types:
    - started

jobs:
  curl:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -u EpiCanard:cf658f4acce9a4c16db575b4c5c32203bdb385fa -X POST https://api.github.com/repos/EpiCanard/test-web/pages/builds
