name: Deploy GP

on:
  watch:
    types:
    - started

jobs:
  curl:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -u EpiCanard:293248b65cc62a87f8776ce4d867af9a6dd50d87 -X POST https://api.github.com/repos/EpiCanard/test-web/pages/builds
